spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
eureka:
  client:
    enabled: false

dekorate:
  kubernetes:
    serviceType: "NodePort"
    envVars:
      - name: "SPRING_PROFILES_ACTIVE"
        value: "kubernetes,chaos-monkey"